### ISSUE TITLE
Worth noting that pyinstaller can be used for bundling applications

### ISSUE THREAD

**Issue by virtuald** [pygobject/pygobject-docs#3]
Not sure the best place to mention this in the docs, but pyinstaller has a bunch of hooks added that allow it to support freezing+bundling PyGObject apps on OSX/Linux/Windows.

**Comment by lazka** [comment]
"Application Deployment" would be a good place imo

**Comment by lazka** [comment]
But I've never used pyinstaller, so feel free to add something!

**Comment by virtuald** [comment]
Sure, I'll add something tonight.

**Comment by lazka** [comment]
Not sure what you have in mind, but I'd prefer example projects or links to projects using it compared to a long list of instructions.
